name: flutter_2048
description: 2048 game.
version: 1.0.3+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations: # 国际化
    sdk: flutter
  intl: ^0.18.1
  cupertino_icons: ^1.0.5 # ios风格图标
  flutter_screenutil: ^5.5.3+2 # 屏幕工具
  device_info: ^2.0.3
  flutter_redux: ^0.10.0 # 状态管理
  redux_thunk: ^0.4.0
  shared_preferences: ^2.0.15
  intro_slider: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true
  
flutter_intl:
  enabled: true