name: flutter_2048
description: 2048 game.
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations: # 国际化
    sdk: flutter
  intl: ^0.17.0
  cupertino_icons: ^1.0.2 # ios风格图标
  flutter_screenutil: ^4.0.3+2 # 屏幕工具
  device_info: ^2.0.2
  flutter_redux: ^0.8.2 # 状态管理
  redux_thunk: ^0.4.0
  shared_preferences: ^2.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

flutter_intl:
  enabled: true
